name: E2E Env Matrix
on:
  push:
  schedule:
    - cron: '0 */3 * * *'
env:
  ENV: prod
jobs:
  on_demand_matrix:
    permissions:
      id-token: write
      contents: read
    name: E2E Matrix
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        url: [
          "https://eth.blockscout.com",
#          "http://gnosis.blockscout.com",
#          "https://gnosis-chiado.blockscout.com",
#          "https://blockscout.com/astar",
#          "https://blockscout.com/shiden",
#          "https://blockscout.com/shibuya",
#          "https://neon.blockscout.com",
#          "https://neon-devnet.blockscout.com",
#          "https://zetachain-athens-3.blockscout.com",
#          "https://pegasus.lightlink.io",
#          "https://phoenix.lightlink.io",
#          "https://explorer.testnet.immutable.com",
#          "https://www.shibariumscan.io",
#          "https://explorer.fuse.io",
#          "https://explorer.fusespark.io",
#          "https://puppyscan.shib.io",
#          "https://optimism-sepolia.blockscout.com",
#          "https://rootstock.blockscout.com",
#          "https://base.blockscout.com",
#          "https://base-sepolia.blockscout.com",
#          "https://etc-mordor.blockscout.com",
#          "https://etc.blockscout.com",
#          "https://explorer.evm.shimmer.network",
#          "https://explorer.evm.testnet.shimmer.network",
#          "https://zksync.blockscout.com",
#          "https://stability-betanet.blockscout.com",
#          "https://optimism.blockscout.com"
        ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: v14.17.0
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install deps
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Cache playwright binaries
        uses: actions/cache@v2
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run playwright
        env:
          BLOCKSCOUT_URL: ${{ matrix.url }}
        run: |
          npm run test:ondemand
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: report
          path: tests/e2e/test-results
defaults:
  run:
    shell: bash
    working-directory: ./tests/e2e
