name: Load Smoke (Metadata)
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  workflow_dispatch:
    inputs:
      test_name:
        description: 'Test name'
        type: string
        default: ci-api-metadata
      url:
        description: 'Environment Root URL'
        required: true
        default: 'https://metadata-test.k8s-dev.blockscout.com'
        type: choice
        options:
          - https://metadata-test.k8s-dev.blockscout.com
      data_file_path:
        description: 'Path to test data file'
        required: true
        default: '../test_data/sepolia.json'
        type: choice
        options:
          - '../test_data/sepolia-metadata.json'
      request_timeout:
        description: 'Global request timeout'
        required: true
        default: 60000
  workflow_call:
    inputs:
      test_name:
        description: 'Test name'
        default: ci-api-metadata
      url:
        description: 'Environment Root URL'
        required: true
        default: 'https://metadata-test.k8s-dev.blockscout.com'
        type: choice
        options:
          - https://metadata-test.k8s-dev.blockscout.com
      data_file_path:
        description: 'Path to test data file'
        required: true
        default: '../test_data/sepolia.json'
        type: choice
        options:
          - '../test_data/sepolia-metadata.json'
      request_timeout:
        description: 'Global request timeout'
        required: true
        default: 60000

jobs:
  smokeMetadata:
    name: Run Blockscout metadata load test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout github repo (+ download lfs dependencies)
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: v14.17.0
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install deps
        run: npm ci
      - name: Run v1/v2 Smoke Test
        env:
          SCENARIO: stressMetadata
          K6_TEST_ID: ${{ inputs.test_name }}-v1
          BASE_URL: ${{ inputs.url }}
          TIMEOUT: ${{ inputs.request_timeout }}
          START_BLOCK: ${{ inputs.start_block }}
          END_BLOCK: ${{ inputs.end_block }}
          TEST_DATA_FILE: ${{ inputs.data_file_path }}
          API_KEY_SEPOLIA: ${{ secrets.API_KEY_SEPOLIA }}
          API_KEY_GOERLI: ${{ secrets.API_KEY_GOERLI }}
          API_KEY_GOERLI_ALLOY: ${{ secrets.API_KEY_GOERLI_ALLOY }}
          API_KEY_GNOSIS: ${{ secrets.API_KEY_GNOSIS }}
          API_KEY_ETH: ${{ secrets.API_KEY_ETH }}
          K6_OUT: ${{ secrets.K6_OUT }}
        run: |
          npm run test:ci
defaults:
  run:
    shell: bash
    working-directory: ./tests/load
