name: Load baseline
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  workflow_dispatch:
    inputs:
      test_name:
        description: 'Test name'
        default: ci-api-v1-baseline
      url:
        description: 'Environment Root URL'
        required: true
        default: 'https://eth-sepolia.blockscout.com/api'
        type: choice
        options:
          - https://eth-sepolia.blockscout.com/api
      start_block:
        description: 'Start block for static requests (default is Sepolia)'
        required: true
        default: 4900358
      end_block:
        description: 'End block for static requests (default is Sepolia)'
        required: true
        default: 4900359
      data_file_path:
        description: 'Path to test data file'
        required: true
        default: '../test_data/sepolia.json'
        type: choice
        options:
          - '../test_data/sepolia.json'
      request_timeout:
        description: 'Global request timeout'
        required: true
        default: 20000
    
jobs:
  v1v2-baseline:
    name: Check out load test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout github repo (+ download lfs dependencies)
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: v14.17.0
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install deps
        run: npm ci
      - name: Run v1 test
        env:
          SCENARIO: stressBackendV1
          K6_TEST_ID: ${{ inputs.test_name }}-v1
          BASE_URL: ${{ inputs.url }}
          TIMEOUT: ${{ inputs.request_timeout }}
          START_BLOCK: ${{ inputs.start_block }}
          END_BLOCK: ${{ inputs.end_block }}
          TEST_DATA_FILE: ${{ inputs.data_file_path }}
          API_KEY: ${{ secrets.API_KEY_SEPOLIA }}
          K6_OUT: ${{ secrets.K6_OUT }}
        run: |
          npm run test:ci
      - name: Run v2 test
        if: always()
        env:
          SCENARIO: stressBackendV2
          K6_TEST_ID: ${{ inputs.test_name }}-v2
          BASE_URL: ${{ inputs.url }}
          TIMEOUT: ${{ inputs.request_timeout }}
          START_BLOCK: ${{ inputs.start_block }}
          END_BLOCK: ${{ inputs.end_block }}
          TEST_DATA_FILE: ${{ inputs.data_file_path }}
          API_KEY: ${{ secrets.API_KEY_SEPOLIA }}
          K6_OUT: ${{ secrets.K6_OUT }}
        run: |
          npm run test:ci
defaults:
  run:
    shell: bash
    working-directory: ./tests/load
