name: Load baseline
on:
  workflow_dispatch:
    
jobs:
  v1v2-baseline:
    name: Check out load test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout github repo (+ download lfs dependencies)
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: v14.17.0
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install deps
        run: npm ci
      - name: Run v1 test
        env:
          K6_TEST_ID: ci-v5.3.3-goerli-api-v1-denorm-transactions
          BASE_URL: https://eth-goerli.blockscout.com/api
          TIMEOUT: 20000
          SCENARIO: stressBackendV1
          API_KEY: ${{ secrets.API_KEY }}
          K6_OUT: ${{ secrets.K6_OUT }}
        run: |
          npm run test:ci
      - name: Run v2 test
        if: always()
        env:
          K6_TEST_ID: ci-v5.3.3-goerli-api-v2-denorm-transactions
          BASE_URL: https://eth-goerli.blockscout.com/api
          TIMEOUT: 20000
          SCENARIO: stressBackendV2
          API_KEY: ${{ secrets.API_KEY }}
          K6_OUT: ${{ secrets.K6_OUT }}
        run: |
          npm run test:ci
defaults:
  run:
    shell: bash
    working-directory: ./tests/load
